### ISSUE TITLE
Use operator @beginWith error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/ModSecurity-apache#19]
When  I send a request_uri is "/index.php?act=seller_center&op=statistics&rand=24954191" and my rule is "SecRule REQUEST_URI "@beginswith /index.php?act=store"
"id:1004,phase:1,pass,nolog,
ctl:ruleRemoveById=949110" but rule id 1004  that his uri is not match the "/index.php?act=seller_center&op=statistics&rand=24954191"，and I found the request I send has match the rule that his id is 1004  why？ The operator beginwith is not a exact match？

**Comment by zimmerle** [comment]
@Hello-Linux that is an specific issue of ModSecurity version 3 for apache?

**Comment by victorhora** [comment]
@Hello-Linux I see that you created the same issue on 3 distinct (but related) ModSecurity projects:

[https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/810](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/810)

[https://github.com/SpiderLabs/ModSecurity/issues/1458](https://github.com/SpiderLabs/ModSecurity/issues/1458)

[https://github.com/SpiderLabs/ModSecurity-apache/issues/19](https://github.com/SpiderLabs/ModSecurity-apache/issues/19)

As others have mentioned, please be more cautious when creating issues by paying closer attention on which kind of issue you have to decide on which project the issue or mailing list it should be. 

And most importantly, please try not to create several issues for the same question. Also try testing a bit more, looking through ModSecurity's reference docs (manual/books/tutorials) and searching for similar issues on Github and the mailing lists before creating a new issue. You have opened 21 new issues in these projects on the last 30 days. You will be surprised that probably many of your questions could already be answered or being handled already in other issues and mailing list e-mails.

As you know these are community projects and everyone takes their time to work improving ModSecurity and helping out each other, so any effort you could do to make everyone's lives easier will be greatly appreciated :)

Thanks!
