### ISSUE TITLE
Intermittent Segmentation Faults

### ISSUE THREAD

**Issue by BP9906** [SpiderLabs/ModSecurity-apache#33]
We tested the ModSecurity-apache connector with libmodsecurity and with the recent fix I was provided, I can get requests going through, but there's a significant volume of segmentation faults that we're seeing. 

I can send a request through Burpsuite and get a response and sometimes I would get a blank response (segfault).  The error was logged in the apache error_log (/var/log/httpd).  We tested this with Centos7 using Apache 2.4 yum install.

**Comment by zimmerle** [comment]
Without further details on the crashes and/or how to reproduce, it will be very hard for us to replicate the problem. Please provide more details on the crashes and/or how to reproduce the issue.
