### ISSUE TITLE
no mod_security3.so in appache modules folder

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [SpiderLabs/ModSecurity-apache#36]
despite of everything compiled fine "make install" does not install mod_security3.so
into the apache modules folder. I have httpd version 2.4.33.
is it a normal v3 behavior?

**Comment by zimmerle** [comment]
Hi @ROBERT-MCDOWELL,

Is the module created?

**Comment by zimmerle** [comment]
The support for ```make install``` was added by: 06273d1b40d9b13b5061c6dcc4d15e0a633e03a0

Thank you @ROBERT-MCDOWELL
