### ISSUE TITLE
No request body

### ISSUE THREAD

**Issue by XuanHuyDuong** [SpiderLabs/ModSecurity-apache#37]
Hello dev teams,

I installed Apache + Modsecurity v3 using this connector. I added CRS and tested it with CRS regression. I had many errors. And then i found that request body cannot be read. I checked source code and compared to Modsecurity v2. Then I saw that it lacked of code before **msc_process_request_body** (in **hook_request_late**). In Modsecurity v2, there is code before that function to read request body.
![image](https://user-images.githubusercontent.com/23336520/40465259-19d16e54-5f4a-11e8-9593-a7b9e490dfc5.png)

**Comment by victorhora** [comment]
Hi @XuanHuyDuong,

Thanks for your comment, but this is known issue and was already discussed at #31 and there's a proposed fix to address this issue at #22. It's currently in experimental stage and you might want to give it a try and let us know the results on the pull request.
