### ISSUE TITLE
Cannot find the module after compiling

### ISSUE THREAD

**Issue by Lud3rik** [SpiderLabs/ModSecurity-apache#38]
Hello,

This is what I did : 

I first compiled libmodsecurity in /usr/local/httpd-2.4.33 and edited the configure to find libmodsecurity

Here is my script

export LIBRARY_PATH=/usr/local/httpd-2.4.33/lib/
cd /somepath/ModSecurity-apache-master
./autogen.sh
./configure --with-apxs=/usr/local/httpd-2.4.33/bin/apxs --with-libmodsecurity=/usr/local/httpd-2.4.33
make -j4
make install

So now I can't find the module and I don't know how to install it with apache

Can you help please?

**Comment by victorhora** [comment]
@Lud3rik Sorry for the long delay :( 

Can you check if the issue persists by applying one of the patches below:

#29
#39
#20

Thanks for letting us know! :)

**Comment by zimmerle** [comment]
make sure that your platform is configured to read the library from the LIBRARY_PATH. Apache env or the platform, should be configured for that.
