### ISSUE TITLE
Modsecurity connector on Centos 6 httpd error " undefined symbol: msc_update_status_code "

### ISSUE THREAD

**Issue by antonioCoco** [SpiderLabs/ModSecurity-apache#40]
Hello,
i compiled libmodesecurity.so v3 and then i also compiled the apache connector.
when i load the module in my httpd.conf with this directive:

`LoadModule security3_module modules/mod_security3.so`
 
I get the following error:

```
Starting httpd: httpd: Syntax error on line 202 of /etc/httpd/conf/httpd.conf: Cannot load /etc/httpd/modules/mod_security3.so into server: /etc/httpd/modules/mod_security3.so: undefined symbol: msc_update_status_code  [FAILED]

```
What msc_update_status_code is? I couldn't found anything relate to that.

I lead to compile by myself the whole library because with the precompiled version in the centos 6 i couldn't use the modsecurity directive:

`SecAuditLogFormat JSON
`

Do you know if with the modsecurity v3 i will have this directive enabled for httpd in centos 6?
Thank you

Antonio

**Comment by victorhora** [comment]
@antonioCoco I haven't experienced this issue before. I'm wondering if has anything to do with failed linking 

Can you check if the issue persists by applying one (or all) of the patches below:

#29 
#39 
#20 

Thanks for letting us know.
