### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by porjo** [SpiderLabs/ModSecurity-apache#45]
I notice the README was last updated 2 years ago. I'm wondering if all the information contained there is still current, for example this statement:

> NOTICE: libmodsecurity is not feature complete and it is not considerable stable, so use is undertaken at your own risk.

That's referring to the core project (not this connector)? If so, then it is at least stable now AFAIK if not feature complete.

Thanks.

**Comment by zimmerle** [comment]
Fixed. Thanks!
