### ISSUE TITLE
Install 3.0.3 modsecurity using repositories

### ISSUE THREAD

**Issue by AnnuA** [SpiderLabs/ModSecurity-apache#49]
I want to install latest stable modsecurity for apache on Ubuntu and Centos.
But when I am installing using 'yum install mod_security' it is installing 2.9.2 version.
The 3.0.3 version is not available in repositories?
I would have to install it by compiling source code only?

**Comment by zimmerle** [comment]
Closing this in favor of SpiderLabs/ModSecurity#1981.
