### ISSUE TITLE
Attack signatures in GET requests not detected

### ISSUE THREAD

**Issue by Goron** [SpiderLabs/ModSecurity-apache#50]
This is in reference to the issue which I created recently [here](https://github.com/SpiderLabs/ModSecurity/issues/1985#issue-391658044) .

The GET requests containing attack signatures are not detected. However the same signatures sent over POST are detected.

Im using 
latest modsecurity version with owasp CRS 3.0 and my environment is setup correct. 
I'm facing this issue since I pulled [this](https://github.com/SpiderLabs/ModSecurity-apache/commit/96fbca43a49c977d12f2a86e2a5ba722b04f0597) commit

**Comment by zimmerle** [comment]
Hi @Goron,

Sorry for the delay. The commit 96fbca43a49c977d12f2a86e2a5ba722b04f0597 was reverted, you should be set now.

**Comment by Goron** [comment]
Hi @zimmerle 

But [this](https://github.com/SpiderLabs/ModSecurity-apache/commit/96fbca43a49c977d12f2a86e2a5ba722b04f0597) commit was supposed to be a fix for POST body handling. However, I reverted the commit and the GET attack signatures were detected. 

That means, I could expect a proper fix in near future for POST attack signatures right?

**Comment by zimmerle** [comment]
Yes, however it may take a while. Keep in mind that the Apache connector is still in beta. For Apache in production, we still recommend the 2.x family.

**Comment by Goron** [comment]
ok thanks
