### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by porjo** [SpiderLabs/ModSecurity-apache#53]
Please update the README with some basic usage instructions. For example, something like this:

> # Usage
> Add the following configuration to your Apache `httpd.conf `
> ``` 
> LoadModule security3_module modules/mod_security3.so
> modsecurity on
> modsecurity_rules_file /path/to/your/modsecurity_rules.conf
> ```

**Comment by victorhora** [comment]
Hi @porjo 

Thanks for the reminder. Basic usage instractions has been added at https://github.com/SpiderLabs/ModSecurity-apache/commit/7a8c78f3d20a4848bdd7e6eb056e808a184b164e

Cheers

**Comment by porjo** [comment]
That's great, thanks!
