### ISSUE TITLE
ModSecurity headers not found

### ISSUE THREAD

**Issue by aminhk** [SpiderLabs/ModSecurity-apache#54]
hi guys
i compiled libmodsecurity and it's installed in /usr/local/modsecurity/lib.
when i tried to compile apache connector it says : Libmodsecurity not found.
I put /usr/local/modsecurity/lib in  /etc/ld.so.conf + ldconfig but didn't work. then i copied * in /usr/local/modsecurity/lib to /usr/lib.

whereis libmodsecurity --> libmodsecurity: /usr/lib/libmodsecurity.so /usr/lib/libmodsecurity.la /usr/lib/libmodsecurity.a /usr/local/lib/libmodsecurity.so /usr/local/lib/libmodsecurity.la /usr/local/lib/libmodsecurity.a

apache-connector  --> ./configure and it says : ModSecurity headers not found

I checked find_libmodsec.m4 and it seems that everything is ok.  I have this dir:/usr/local/modsecurity/
and modsecurity is in : /usr/local/modsecurity/include/modsecurity. but i don't know what is wrong ?
im tired of testing if anyone could help me i would appreciate it.

**Comment by victorhora** [comment]
Hi @aminhk 

Did you find a workaround for the issue you reported? 

You may want to look into https://github.com/SpiderLabs/ModSecurity-apache/issues/47 as a similar issue is being discussed.

**Comment by zimmerle** [comment]
Hi @aminhk,

There are two things that apache connector is looking for:  **the library** and the **headers**. It seems like you made it successfully find the library into the _/usr/_ folder, but not the headers. 

Did you have the chance to use the ```--prefix``` during libModSecurity compilation?
