### ISSUE TITLE
./configure argument "CC" won't work

### ISSUE THREAD

**Issue by Neko-Chang-Taiwan** [SpiderLabs/ModSecurity-apache#60]
Hi All:

I trying use modsecurity3 with Apache 2.4 on FreeBSD 12.0 amd64.
I pulled latest commit for modsecurity-apache connector.

FreeBSD default compiler: Clang/LLVM 6.0.1
So part of ./configure result as below.
.# ./configure --with-libmodsecurity=/usr/local
checking for gcc... 
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking whether cc understands -c and -o together... yes
checking dependency style of cc... none
checking how to run the C preprocessor... cc -E
checking for ANSI C header files... yes

Later, test the issue #59  tried to build by "gcc8"
Part of ./configure result as below.
.# ./configure --with-libmodsecurity=/usr/local CC=/usr/local/bin/gcc8
checking for gcc... /usr/local/bin/gcc8
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking whether we are using the GNU C compiler... yes
checking whether /usr/local/bin/gcc8 accepts -g... yes
checking for /usr/local/bin/gcc8 option to accept ISO C89... none needed
checking whether /usr/local/bin/gcc8 understands -c and -o together... yes
checking dependency style of /usr/local/bin/gcc8... none
checking how to run the C preprocessor... /usr/local/bin/gcc8 -E
checking for gcc... (cached) /usr/local/bin/gcc8
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/local/bin/gcc8 accepts -g... (cached) yes
checking for /usr/local/bin/gcc8 option to accept ISO C89... (cached) none needed
checking whether /usr/local/bin/gcc8 understands -c and -o together... (cached) yes
checking dependency style of /usr/local/bin/gcc8... (cached) none

But make always use system "cc"(Clang/LLVM 6.0.1)
Argument "CC" won't work look like.

Please let me know what is going wrong.
Thanks a lot.

**Comment by zimmerle** [comment]
Hi @Neko-Chang-Taiwan,

Please double-check if there inst different symbol links for a single compiler in your machine. I was not able to reproduce:
```
./configure CC=clang
```
Outputs
```
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o

```

**Comment by Neko-Chang-Taiwan** [comment]
Hi @zimmerle

Thanks your replied.
I got same result with yours.

I think ./confirure can be handle system default CC and show information as your result before.
But shall be assign explicitly look like.

Thanks your help a lot.
