### ISSUE TITLE
make failed  libtool: line 848: cc: command not found

### ISSUE THREAD

**Issue by mf33a2t556d** [SpiderLabs/ModSecurity-apache#62]
on Solaris 11 make failed

uname -a
SunOS 5.11 11.3 sun4v sparc sun4v

./autogen.sh 
/usr/share/aclocal/aalib.m4:12: warning: underquoted definition of AM_PATH_AALIB
/usr/share/aclocal/aalib.m4:12:   run info '(automake)Extending aclocal'
/usr/share/aclocal/aalib.m4:12:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
configure.ac:8: installing `./install-sh'
configure.ac:8: installing `./missing

./configure --with-apache=/opt/IBMIHS/bin/httpd --with-apxs=/opt/IBMIHS/bin/apxs --with-libmodsecurity=/usr/local/modsecurity
checking for a BSD-compatible install... /usr/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
configure: looking for Apache module support via DSO through APXS
configure: found APXS at /opt/IBMIHS/bin/apxs
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/ggrep
checking for egrep... /usr/bin/ggrep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
configure: looking for libmodsecurity
checking for msc_init in -lmodsecurity... yes
checking modsecurity/modsecurity.h usability... yes
checking modsecurity/modsecurity.h presence... yes
checking for modsecurity/modsecurity.h... yes
checking if apache is wanted... yes
expr: syntax error
expr: syntax error
checking apache modules... in /opt/IBMIHS/modules
checking for perl... /usr/bin/perl
Loaded Modules:
 core_module (static)
 mpm_worker_module (static)
 http_module (static)
 suexec_module (static)
 so_module (static)
 authz_host_module (shared)
 auth_basic_module (shared)
 authn_file_module (shared)
 authz_user_module (shared)
 include_module (shared)
 log_config_module (shared)
 env_module (shared)
 expires_module (shared)
 headers_module (shared)
 unique_id_module (shared)
 setenvif_module (shared)
 proxy_module (shared)
 proxy_http_module (shared)
 mime_module (shared)
 autoindex_module (shared)
 asis_module (shared)
 info_module (shared)
 cgid_module (shared)
 dir_module (shared)
 actions_module (shared)
 alias_module (shared)
 rewrite_module (shared)
 status_module (shared)
 mpmstats_module (shared)
 backtrace_module (shared)
 whatkilledus_module (shared)
Syntax OK
Loaded Modules:
 core_module (static)
 mpm_worker_module (static)
 http_module (static)
 suexec_module (static)
 so_module (static)
 authz_host_module (shared)
 auth_basic_module (shared)
 authn_file_module (shared)
 authz_user_module (shared)
 include_module (shared)
 log_config_module (shared)
 env_module (shared)
 expires_module (shared)
 headers_module (shared)
 unique_id_module (shared)
 setenvif_module (shared)
 proxy_module (shared)
 proxy_http_module (shared)
 mime_module (shared)
 autoindex_module (shared)
 asis_module (shared)
 info_module (shared)
 cgid_module (shared)
 dir_module (shared)
 actions_module (shared)
 alias_module (shared)
 rewrite_module (shared)
 status_module (shared)
 mpmstats_module (shared)
 backtrace_module (shared)
 whatkilledus_module (shared)
Syntax OK
Found Apache with MPM Worker, .
./configure[4396]: [: argument expected
./configure[4399]: [: argument expected
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) none
configure: creating ./config.status
config.status: creating Makefile
config.status: creating build/apxs-wrapper
config.status: creating tests/regression/server_root/conf/httpd.conf
config.status: creating tests/regression/misc/40-secRemoteRules.t
config.status: creating tests/regression/misc/60-pmfromfile-external.t
config.status: creating tests/regression/misc/50-ipmatchfromfile-external.t
config.status: creating tests/run-regression-tests.pl
config.status: executing depfiles commands

make
chmod +x build/apxs-wrapper
build/apxs-wrapper
/opt/IBMIHS/build/libtool --silent --mode=compile cc -prefer-pic   -DSOLARIS2=10 -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D_LARGEFILE64_SOURCE -g -I/opt/IBMIHS/include  -I/opt/IBMIHS/include   -I/opt/IBMIHS/include   -fPIC -O0 -I/usr/local/modsecurity/include/  -c -o src/mod_security3.lo src/mod_security3.c && touch src/mod_security3.slo
/opt/IBMIHS/build/libtool: line 848: cc: command not found
apxs:Error: Command failed with rc=65536
.
*** Error code 1
make: Fatal error: Command failed for target `all'

**Comment by victorhora** [comment]
I think your issue might be related with https://github.com/SpiderLabs/ModSecurity-apache/issues/60. Seems like the scripts are failing to find your compiler. Can you check if you get better results with LLVM instead of GCC?

**Comment by victorhora** [comment]
Closing due to lack of feedback from reporter. If the issue persists, let us know. Thanks!
