### ISSUE TITLE
Build and release binaries on GitHub

### ISSUE THREAD

**Issue by soufianebenali** [SpiderLabs/ModSecurity-apache#64]
We are refactoring the [modsecurity-docker](https://github.com/CRS-support/modsecurity-docker) repository, and we saw that the ModSecurity-apache binary is built in the Dockerfile from source.

And while the installation process is simple, we would prefer to simply install a binary or a package for a target platform, for several reasons:

- Building, testing and attaching a version number should be part of the release process of the software, not the build process of a Docker image.
- ModSecurity binaries we ship with an image should be available also separately, outside of the Docker image.
- If there are any dependencies they should be covered by the software's build process to make installation easy on and independent from installation processes of ModSecurity's target platforms.

Are you planning on releasing ModSecurity-apache packages [here on GitHub](https://github.com/SpiderLabs/ModSecurity-apache/releases)? Is there anything that we can help you with getting that realized?

**Comment by zimmerle** [comment]
Hi @soufianebenali ,

The packages for ModSecurity are distribution (and platform) dependent, we trust the distributions to keep the packages up to date. Maybe, it is the case to install the distribution package in the docker image.

**Comment by soufianebenali** [comment]
Hi @zimmerle,

Thank you for clarifying. Can you please link to the packages for debian and alpine?

**Comment by zimmerle** [comment]
I don't think that ModSecurity-apache was packed already as the project never had a release.
